package com.github.butterbrother.ews.redirector.graphics;

import javax.swing.*;
import java.awt.*;

/**
 * Created by user on 18.01.2016.
 */
public class FilterEditor {
    private JPanel FilterEditorForm;
    private JLabel FilterNameLabel;
    private JTextField FilterNameInput;
    private JLabel RuleOperatorLabel;
    private JComboBox RuleOperatorList;
    private JPanel UpLevel;
    private JPanel RuleEditLevel;
    private JComboBox RuleType;
    private JComboBox RuleOperator;
    private JTextField RuleValue;
    private JPanel RuleTablesLevel;
    private JPanel RulesTablePanel;
    private JScrollPane RulesTableScroll;
    private JPanel RulesControl;
    private JButton AddRuleButton;
    private JButton RemoveRuleButton;
    private JButton DropRulesButton;
    private JButton SaveFilterButton;
    private JPanel FilterControlLevel;
    private JButton CancelFilterButton;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        FilterEditorForm = new JPanel();
        FilterEditorForm.setLayout(new GridBagLayout());
        UpLevel = new JPanel();
        UpLevel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 5, 0, 0);
        FilterEditorForm.add(UpLevel, gbc);
        FilterNameLabel = new JLabel();
        FilterNameLabel.setHorizontalAlignment(11);
        FilterNameLabel.setHorizontalTextPosition(10);
        FilterNameLabel.setText("Filter name:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        UpLevel.add(FilterNameLabel, gbc);
        FilterNameInput = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 100;
        UpLevel.add(FilterNameInput, gbc);
        RuleOperatorLabel = new JLabel();
        RuleOperatorLabel.setText("Logical operator:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        UpLevel.add(RuleOperatorLabel, gbc);
        RuleOperatorList = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 100;
        UpLevel.add(RuleOperatorList, gbc);
        FilterControlLevel = new JPanel();
        FilterControlLevel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.weightx = 0.3;
        gbc.fill = GridBagConstraints.BOTH;
        UpLevel.add(FilterControlLevel, gbc);
        SaveFilterButton = new JButton();
        SaveFilterButton.setText("Save");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        FilterControlLevel.add(SaveFilterButton, gbc);
        CancelFilterButton = new JButton();
        CancelFilterButton.setText("Cancel");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        FilterControlLevel.add(CancelFilterButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        FilterControlLevel.add(spacer1, gbc);
        RuleEditLevel = new JPanel();
        RuleEditLevel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        FilterEditorForm.add(RuleEditLevel, gbc);
        RuleEditLevel.setBorder(BorderFactory.createTitledBorder("Rule:"));
        RuleType = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        RuleEditLevel.add(RuleType, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        RuleEditLevel.add(spacer2, gbc);
        RuleOperator = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 0.3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        RuleEditLevel.add(RuleOperator, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        RuleEditLevel.add(spacer3, gbc);
        RuleValue = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.weightx = 0.3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        RuleEditLevel.add(RuleValue, gbc);
        RuleTablesLevel = new JPanel();
        RuleTablesLevel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        FilterEditorForm.add(RuleTablesLevel, gbc);
        RulesTablePanel = new JPanel();
        RulesTablePanel.setLayout(new CardLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 400;
        gbc.ipady = 200;
        RuleTablesLevel.add(RulesTablePanel, gbc);
        RulesTableScroll = new JScrollPane();
        RulesTableScroll.setVerticalScrollBarPolicy(22);
        RulesTablePanel.add(RulesTableScroll, "Card1");
        RulesControl = new JPanel();
        RulesControl.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        RuleTablesLevel.add(RulesControl, gbc);
        AddRuleButton = new JButton();
        AddRuleButton.setText("+");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        RulesControl.add(AddRuleButton, gbc);
        RemoveRuleButton = new JButton();
        RemoveRuleButton.setText("-");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        RulesControl.add(RemoveRuleButton, gbc);
        DropRulesButton = new JButton();
        DropRulesButton.setText("X");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        RulesControl.add(DropRulesButton, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.VERTICAL;
        RulesControl.add(spacer4, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return FilterEditorForm;
    }
}
